[package]
name = "eve-gql"
version = "0.1.0"
authors = ["Darius Bakunas-Milanowski <bakunas@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-rc"
juniper = "0.12.0"
futures = "0.1.27"
serde = "1.0.91"
serde_json = "1.0.39"
serde_derive = "1.0.91"
env_logger = "0.6.1"