version: '3.3'

services:
  gql:
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'eve-gql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - eve-db:/var/lib/mysql
volumes:
  eve-db: